apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongodb-test
  namespace: eval   
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: my-mongodb-test
  strategy:
    type: Recreate
  template:  
    metadata:
      labels:
        app: my-mongodb-test
    spec:
      containers: 
        - name: mongo
          image: mongo:4.0.9
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /mnt/data/db
              name: task-pv-storage
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      restartPolicy: Always