apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "strapi"
        - name: POSTGRES_DB
          value: "strapi"
        ports:
        - containerPort: 5432