apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: eval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: strapi
        image: kevin91270/vuejs-eval:001
        imagePullPolicy: Always
        ports:
        - containerPort: 1337