apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: eval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: strapi
        image: strapi/strapi
        imagePullPolicy: Always
        env:
        - name : DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres.eval.svc.cluster.local"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "strapi"            
        - name: EXTRA_ARGS
          value: "strapi new"
        ports:
        - containerPort: 1337
