apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
  namespace: eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: vuejs
        image: mehdimd/vuejs:01
        imagePullPolicy: Always
        ports:
        - containerPort: 8080