apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: eval
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain