apiVersion: v1
kind: Service
metadata:
  name: my-mongodb-service-test
  namespace: eval
spec:
  clusterIP: 10.96.202.227
  selector:
    app: my-mongodb
  ports:
  - port: 27017
    targetPort: 27017 
    nodePort: 32003
    protocol: TCP
  type: NodePort