apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: eval
spec:
  clusterIP: 10.96.202.227
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32002
  type: NodePort